Adding API retry and fixing heritage of npyscreen
outscale-dev/osc-tui pull request #45
Opened 2021-04-09 12:13 UTC by BadyJoke

### Changes

- Adding a retry over the ReadVm API call. Programm no longer crash
- Changing heritage of the App class by NPSAppManaged

2021-04-09 13:18 UTC, outscale-mgo requested changes

2021-04-09 13:18 UTC, outscale-mgo commented on osc_tui/instancesGrid.py
> +                except TypeError:
in fact I'm sceptical that GATEWAY would return a type error if the call fail
form=self.form <- wonder if the error doesn't came from that ?

Maybe use a break instead of having a tmp variable retry ?

2021-04-12 09:22 UTC, BadyJoke commented on osc_tui/instancesGrid.py
> +            data = reply["Vms"]
The SDK call can return None so we make a while loop until the reply is different of None

2021-04-12 09:26 UTC, BadyJoke commented on osc_tui/main.py
> +class App(npyscreen.NPSAppManaged):
Using StandardApp is now deprecated and it makes the application crash at the start. The documentation of npyscreen recommends using NPSAppManaged.

2021-04-13 10:08 UTC, closed without merging