InstanceGrid : Retry API call if reply is None
outscale-dev/osc-tui pull request #48
Opened 2021-04-13 10:07 UTC by BadyJoke

### Explanation

The application crashed when trying to see instances. The code now loops until the reply is different of None

2021-04-13 12:57 UTC, outscale-mgo requested changes

2021-04-13 12:57 UTC, outscale-mgo commented on osc_tui/instancesGrid.py
> +                reply = main.GATEWAY.ReadVms(form=self.form)
could you swap the sleep and the `reply = main.GATEWAY.ReadVms(form=self.form)` please.
Because otherwise, 2 first times have no sleep.

Otherwise a maximum number of retry would be nice

2021-04-13 20:03 UTC, outscale-mgo requested changes

2021-04-13 20:03 UTC, outscale-mgo commented on osc_tui/instancesGrid.py
> +                time.sleep(0.5)
thanks, can you swap the sleep and the ReadVms, like this V:
```
reply = main.GATEWAY.ReadVms(form=self.form)
time.sleep(0.5)
```

is in case you enter the loop the code will do: readVm -> sleep -> readVm
Because in the current state it do readVm -> readVm -> sleep

2021-04-14 07:43 UTC, BadyJoke commented on osc_tui/instancesGrid.py
> +                time.sleep(0.5)
I think it is already doing : 
readVm -> sleep -> readVm

2021-04-14 07:52 UTC, merged