Polishing : added key bindings
outscale-dev/osc-tui pull request #53
Opened 2021-05-28 09:27 UTC by BadyJoke

Added the following key bindings : 

- CTRL + Q  -> quit
- CTRL + H  -> show help pop-up

2021-05-28 09:51 UTC, outscale-mgo requested changes
Thanks
Would be nice if binding would work in profile select screen too.  (in which case 'q' would quit)

2021-05-28 09:51 UTC, outscale-mgo commented on osc_tui/mainForm.py
> +        self.add_handlers({"^Q": quit})
- I'm pretty sure 'q' is more common than "ctrl-Q"
- Maybe use 'h' instead of ctrl-H
- usage of Q and H in upper case make it harder to use, maybe bind both ?
- Also this directly quit the program, maybe add a q that would return to main profile select and keep ctrl-q for instant quit ?

2021-06-11 08:19 UTC, BadyJoke commented on osc_tui/mainForm.py
> +        self.add_handlers({"^Q": quit})
Note that the shortcut is ctrl+q but npyscreen require to note the letter in uppercase.

2021-06-11 14:29 UTC, outscale-mgo commented
merged manually

2021-06-11 14:29 UTC, closed without merging